a=int(input("Enter the value of a: "))
b=int(input("Enter the value of b: "))
c=int(input("Enter the value of c: "))
d=int(input("Enter the value of d: "))
z1=complex(a,b)
z2=complex(c,d)
print("sum of two complex numbers: ",z1+z2)
