from tkinter import *
root=Tk()
def get():
    print(uservalue.get())
    print(passvalue.get())
root.geometry("600x400")
user=Label(root,text="username")
password=Label(root,text="password")
user.grid()
password.grid(row=1)
uservalue=StringVar()
passvalue=StringVar()
userentry=Entry(root,textvariable=uservalue)
passentry=Entry(root,textvariable=passvalue)
userentry.grid(row=0,column=1)
passentry.grid(row=1,column=1)
b1=Button(text="Submit",command=get)
b1.grid()
root.mainloop()