from tkinter import *
root=Tk()
def getvalue():
    print(f"{uservalue.get(),passvalue.get(),phonevalue.get(),emailvalue.get(),paymentmodevalue.get(),ordervalue.get()}")
    with open("records.txt","a") as f:
        f.write(f"{uservalue.get(),passvalue.get(),phonevalue.get(),emailvalue.get(),paymentmodevalue.get(),ordervalue.get()}\n")
root.geometry("600x400")
Label(root,text="Welcome to Reet Kamlay Food Center").grid(row=0,column=3)
user=Label(root,text="Username")
password=Label(root,text="Password")
phone=Label(root,text="Phone")
email=Label(root,text="Email")
paymentmode=Label(root,text="Paymentmode")
user.grid(row=1,column=2)
password.grid(row=2,column=2)
phone.grid(row=3,column=2)
email.grid(row=4,column=2)
paymentmode.grid(row=5,column=2)
uservalue=StringVar()
passvalue=StringVar()
phonevalue=StringVar()
emailvalue=StringVar()
paymentmodevalue=StringVar()
ordervalue=IntVar()
userentry=Entry(root,textvariable=uservalue)
passentry=Entry(root,textvariable=passvalue)
phoneentry=Entry(root,textvariable=phonevalue)
emailentry=Entry(root,textvariable=emailvalue)
paymentmodeentry=Entry(root,textvariable=paymentmodevalue)
userentry.grid(row=1,column=3)
passentry.grid(row=2,column=3)
phoneentry.grid(row=3,column=3)
emailentry.grid(row=4,column=3)
paymentmodeentry.grid(row=5,column=3)
orderentry=Checkbutton(text="Want to preorder food",variable=ordervalue)
orderentry.grid(row=6,column=3)
Button(text="Submit",command=getvalue).grid(row=7,column=3)
root.mainloop()