from tkinter import *
import tkinter.messagebox as tmsg
root=Tk()
def getdollar():
    print(f"we have credited {myslider2.get()} dollars to your bank")
    tmsg.showinfo("Amount Credited",f"we have credited {myslider2.get()} dollars to your bank")
def myfunc():
    tmsg.showinfo("Help","This is my Software")
def rate():
    value=tmsg.askquestion("Rate Us","How was your Experience")
    if(value=="yes"):
        msg="Great: Rate Us on Play Store please"
    else:
        msg="Please Let us know about your problem"
    tmsg.showinfo("Experience",msg)
root.geometry("1000x1000")
mainmenu=Menu(root)
m1=Menu(mainmenu,tearoff=0)
m2=Menu(m1,tearoff=0)
m3=Menu(m1,tearoff=0)
m4=Menu(m1,tearoff=0)
m5=Menu(m4,tearoff=0)
m6=Menu(m4,tearoff=0)
m6.add_command(label="Default")
m6.add_command(label="Show Profile Contents")
m6.add_separator()
m6.add_command(label="Create Profile")
m6.add_command(label="Delete Profile")
m6.add_separator()
m6.add_command(label="Export Profile")
m6.add_command(label="Import Profile")
m5.add_command(label="Color Theme")
m5.add_command(label="File Icon Theme")
m5.add_command(label="Product Icon Theme")
m2.add_command(label="Reopen Closed Editor")
m2.add_command(label="More...")
m3.add_command(label="Export Profile(Default)...")
m3.add_command(label="Import Profile...")
m4.add_cascade(label="Profiles(Default)",menu=m6)
m4.add_command(label="Settings")
m4.add_command(label="Extensions")
m4.add_command(label="Keyboard Shortcuts")
m4.add_command(label="Configure User Snippets")
m4.add_command(label="User Tasks")
m4.add_cascade(label="Theme",menu=m5)
m4.add_separator()
m4.add_command(label="Online Service Settings")
m4.add_separator()
m4.add_command(label="Backup and Sync Settings...")
m1.add_command(label="New Text File")
m1.add_command(label="New File...")
m1.add_command(label="New Window")
m1.add_separator()
m1.add_command(label="Open File...")
m1.add_command(label="OPen Folder...")
m1.add_command(label="OPen Workspace from File...")
m1.add_cascade(label="Open Recent",menu=m2)
m1.add_separator()
m1.add_command(label="Add Folder to Workspace...")
m1.add_command(label="Save Workspace As...")
m1.add_command(label="Duplicate Workspace")
m1.add_separator()
m1.add_command(label="Save")
m1.add_command(label="Save As...")
m1.add_command(label="Save All")
m1.add_separator()
m1.add_cascade(label="Share",menu=m3)
m1.add_separator()
m1.add_command(label="Auto Save")
m1.add_cascade(label="Preferences",menu=m4)
m1.add_separator()
m1.add_command(label="Revert File")
m1.add_command(label="Close Editor")
m1.add_command(label="Close Folder")
m1.add_command(label="Close Window")
m1.add_separator()
m1.add_command(label="Exit",command=quit)
mainmenu.add_cascade(label="File",menu=m1)
m7=Menu(mainmenu,tearoff=0)
m7.add_command(label="About",command=myfunc)
m7.add_command(label="Rate Us",command=rate)
mainmenu.add_cascade(label="Help",menu=m7)
root.config(menu=mainmenu)
Label(root,text="How many dollars do you want?").pack()
myslider2=Scale(root,from_=0,to=100,orient=HORIZONTAL).pack()
Button(root,text="Get Dollars!",command=getdollar).pack()
root.mainloop()